### ISSUE TITLE
Cloudflare Issues

### ISSUE THREAD

**Issue by philip-ulrich** [yariplus/minecraft-nodebb-integration#10]
http://d.l33t.tech/18zOO/2kRihqGt

When using my cloudflare url, it does not work properly. When using my direct url, it does. I don't want my "live" url to be displayed though. Is there a way to let this work with cloudflare or could there be a way added to do a "live" url?

**Comment by yariplus** [comment]
I think adding a 'live' config option should work.

I'll try to add it tomorrow, but I'm getting ready to leave on vacation, apologies if I forget to do it.

**Comment by philip-ulrich** [comment]
No worries. Cheers mate!

**Comment by yariplus** [comment]
https://github.com/yariplus/bukkit-plugin-nodebb-integration/releases/tag/v0.7.0-beta.9

Added configs for websockets.

Use command `/nodebb live {url}`

It works on my server, but I haven't tested it thoroughly.

**Comment by philip-ulrich** [comment]
Tim to the rescue once again! Thanks man.
