### ISSUE TITLE
"address" option in "socketio" needs to be manually set, else throws "xhr poll error"

### ISSUE THREAD

**Issue by Aziroshin** [yariplus/minecraft-nodebb-integration#11]
**Problem Description:**
The "address" option in the "socketio" section needs to be manually set to the NodeBB URL in the config file for the plugin to connect. If that isn't done, the following error is produced repeatedly in an interval of a few seconds:

> `[23:41:45 INFO]: [NodeBB-Integration] io.socket.engineio.client.EngineIOException: xhr poll error
> [23:41:50 INFO]: [NodeBB-Integration] Error connecting to the forum.`

**Environment:**
- **Server Software:** SpigotMC
- **Server Software Version:** git-Spigot-a1b8bf3-f01861f (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)
- **NodeBB version:** 1.0.2
- **plugin version:** v0.7.0-beta.9
- **HTTP protocol used:** HTTPS
- **nginx version:** nginx/1.4.6 (Ubuntu).
- **Output of nginx -V:** http://pastebin.com/bUBiR6SA
- **Java version:** "1.7.0_95"
  - **Additional Information:** OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.2)
    OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

**Comment by yariplus** [comment]
Thanks for all the details. I believe I fixed this in a recent commit, I just need to do some testing and cleanup.

Just an fyi, the next version will likely require Java 8.

**Comment by yariplus** [comment]
Are you able to update to Java 8?

**Comment by yariplus** [comment]
I published a new release that should fix this, but requires Java 8.

If you for some reason cannot update to Java 8, let me know.

**Comment by yariplus** [comment]
Closing this since addressed.

Plugin uses the forum url by default, and the socket.io address can be set in game with `/nodebb live {URL}`
