### ISSUE TITLE
Create a Spigot Resource

### ISSUE THREAD

**Issue by philip-ulrich** [yariplus/minecraft-nodebb-integration#12]
I (and many others) depend on spigot to get plugin update notifications. Would you be willing to start publishing this on spigot as well? <3

**Comment by yariplus** [comment]
Absolutely. :)

As soon as 0.7.0 stable is ready, I plan on pushing updates to spigot regularly.

All the major bugs are already addressed, so it shouldn't be too much longer.

**Comment by yariplus** [comment]
Okay, all uploaded. Appreciate any comments on how to improve the look of the page, and on any info that is wrong or missing.

https://www.spigotmc.org/resources/nodebb-integration.23166/

**Comment by phit** [comment]
image doesn't work, looks like github camo doesn't allow hotlinking

**Comment by yariplus** [comment]
Should be working now.
