### ISSUE TITLE
java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by Couby** [yariplus/minecraft-nodebb-integration#27]
Hi,
I encountered the error in title trying to get minecraft-nodebb-integration working with my fresh new server.

I first had an error with Vault missing as dependency, so I added it (I could propose a readme commit precising it).

And now I have this new error : 

> 04:54:18 INFO]: This server is running CraftBukkit version git-Bukkit-6053c5c (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
> [04:54:19 ERROR]: Could not load 'plugins/nodebb-integration-universal-0.7.3.jar' in folder 'plugins'
> org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/radiofreederp/nodebbintegration/NodeBBIntegrationBukkit : Unsupported major.minor version 52.0
>     at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[bukkit.jar:git-Bukkit-6053c5c]
>     at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[bukkit.jar:git-Bukkit-6053c5c]
>     at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [bukkit.jar:git-Bukkit-6053c5c]
>     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:294) [bukkit.jar:git-Bukkit-6053c5c]
>     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.<init>(CraftServer.java:256) [bukkit.jar:git-Bukkit-6053c5c]
>     at net.minecraft.server.v1_10_R1.PlayerList.<init>(PlayerList.java:70) [bukkit.jar:git-Bukkit-6053c5c]
>     at net.minecraft.server.v1_10_R1.DedicatedPlayerList.<init>(SourceFile:14) [bukkit.jar:git-Bukkit-6053c5c]
>     at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:184) [bukkit.jar:git-Bukkit-6053c5c]
>     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:514) [bukkit.jar:git-Bukkit-6053c5c]
>     at java.lang.Thread.run(Thread.java:745) [?:1.7.0_101]
> Caused by: java.lang.UnsupportedClassVersionError: com/radiofreederp/nodebbintegration/NodeBBIntegrationBukkit : Unsupported major.minor version 52.0
>     at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_101]
>     at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[?:1.7.0_101]
>     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_101]
>     at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_101]
>     at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_101]
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_101]
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_101]
>     at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_101]
>     at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_101]
>     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[bukkit.jar:git-Bukkit-6053c5c]
>     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[bukkit.jar:git-Bukkit-6053c5c]
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_101]
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_101]
>     at java.lang.Class.forName0(Native Method) ~[?:1.7.0_101]
>     at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_101]
>     at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[bukkit.jar:git-Bukkit-6053c5c]
>     at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[bukkit.jar:git-Bukkit-6053c5c]
>     ... 9 more

Is it due to Bukkit version number or related to a language settings ?

Regards.

**Comment by yariplus** [comment]
It's complaining you are not on Java 8. If you for some reason cannot upgrade to Java 8, try using the legacy version here:
https://github.com/yariplus/minecraft-nodebb-integration/releases/download/v0.7.3/nodebb-integration-legacy-0.7.3.jar

**Comment by Couby** [comment]
That's it !
Thanks a lot @yariplus :)
