### ISSUE TITLE
SpongeForge server install

### ISSUE THREAD

**Issue by Couby** [yariplus/minecraft-nodebb-integration#34]
Hi,

Sorry if this is obvious :disappointed: I don't find how to install the plugin with a SpongeForge server.

I tried to put it in plugins and mods folder, I get this message : 
```
[06:47:22] [Server thread/INFO] [FML]: FML has found a non-mod file nodebb-integration-universal-0.7.3.1.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
```

**Comment by yariplus** [comment]
You may need to use the 0.8.0 version here on GitHub under the releases tab.

**Comment by Couby** [comment]
Just tried with the 0.8.0, same result : 
`[18:15:25] [Server thread/INFO] [FML]: FML has found a non-mod file nodebb-integration-universal-0.8.0.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.`

Using **forge-1.10.2-12.18.3.2281** and **spongeforge-1.10.2-2281-5.2.0-BETA-2558**.

**Comment by Couby** [comment]
0.8.0-alpha.10 precisely, I renamed the jar file.

**Comment by yariplus** [comment]
Word. I'll take a look at it tonight. Thanks for trying that.

**Comment by Couby** [comment]
Thanks :smile:

**Comment by phit** [comment]
that message has nothing to do with the plugin, FML will always print that for sponge plugins.. I've been using `nodebb-integration-universal-0.8.0-alpha.10.jar` with SpongeForge 1.10 and 1.11 with no issues, you sure it hasn't loaded? you can check with `/sponge plugins` or just running `/nodebb`

**Comment by Couby** [comment]
Unknown command for both. Not a surprise for `/nodebb` as I already tried, but more surprising for sponge... Could the problem come from sponge ?

**Comment by phit** [comment]
Post your fml-server-latest.log, I'm on the exact same sponge version and am not having any issues.

![](https://i.imgur.com/2ZMhWQz.png)

edit: `/sponge plugins` should work, if it doesn't Sponge isn't even loaded

**Comment by yariplus** [comment]
Confirmed 1.11 and 1.12 also working. Let's see those logs! :)

**Comment by Couby** [comment]
"Unknown command" for both. :cry: 
Really strange for sponge.
Could come from my server install.

**Comment by Couby** [comment]
Damn, looks like I didn't install the right java :roll_eyes: 
`[18:14:18] [main/INFO] [FML/]: Java is OpenJDK 64-Bit Server VM, version 1.7.0_131, running on Linux:amd64:4.4.19-1-pve, installed at /usr/lib/jvm/java-7-openjdk-amd64/jre`
Trying to fix this first.
Thanks a lot for this direction.

**Comment by Couby** [comment]
That was it. Sorry for that.

Thanks again for your help @yariplus @phit
