### ISSUE TITLE
Commands don't function - spigot 1.8.8

### ISSUE THREAD

**Issue by comfysquirrel** [yariplus/minecraft-nodebb-integration#4]
The plugin appears to load, but none of the commands do anything. typing `/nodebb` or `/nodebb <anything>` just returns a line of text in chat that says `/nodebb`. (I am opped)

I thought it was one of my other plugins breaking it somehow, but I installed a fresh server spigot and no other plugins, and there is still the same issue.

Here is a log file http://pastebin.com/a37te0Uw

**Comment by comfysquirrel** [comment]
Also, I noticed the config is not generating the `PluginMessages:` section, not sure if it is supposed to or if that is related to this issue.

**Comment by yariplus** [comment]
It looks like you have the wrong file, I must have uploaded the wrong jar. Where did you download the plugin from?

**Comment by comfysquirrel** [comment]
Hmm, I downloaded the file from BukkitDev. I also tried the file from GitHub Releases, the same thing happened.

**Comment by yariplus** [comment]
Dang it, you're right, both of them are derpped. Try the new version I just posted.
https://github.com/yariplus/bukkit-plugin-nodebb-integration/releases/download/v0.7.0-beta/nodebb-integration-0.7.0-beta.jar

**Comment by comfysquirrel** [comment]
Wonderful, it works flawlessly! Thanks for responding so quickly! :)
