### ISSUE TITLE
Change Registration Method

### ISSUE THREAD

**Issue by philip-ulrich** [yariplus/minecraft-nodebb-integration#8]
Having the user enter their password into chat is super sketchy and the password shows up in server logs.. plus if user mistypes (forgets / or something) then password is spammed to server. Is it possible to do something like enjin does and generate a unique key for the user to enter on the forum or vice versa?

**Comment by yariplus** [comment]
Yeah, I agree. I didn't think that part through very well.

Keys sound like a good idea. I already implement keys on forum the admin side, should be able to use the same pattern for the users' settings page.

**Comment by philip-ulrich** [comment]
It's alright. In your defense, I think all the other forum integration plug-ins started out that way. It's definitely the easier thing to do too because I imagine it hooks into the api very easily. 

I'm about 2 weeks out from launching a small project and the current status of this plug-in makes it unusable for me. I don't know if it fits in your time line, but I would love to use this plug-in because NodeBB is by far the best forum software. No pressure, but you'd be my best friend for roughly 12 hours following the next version if you get this fixed here shortly. :D

**Comment by yariplus** [comment]
Should be done tomorrow, just a few more issues I need to figure out.

**Comment by philip-ulrich** [comment]
Thanks Tim. You're a fantastic person! <3

**Comment by yariplus** [comment]
Okay, new key-based system is ready for use.
https://github.com/yariplus/bukkit-plugin-nodebb-integration/releases/tag/v0.7.0-beta.7

I changed a lot of the internals, so there's probably a few bugs I didn't catch. I'll keep this open for a little while for any initial bug reports.

**Comment by philip-ulrich** [comment]
Sweet. I'll be testing it out tonight or tomorrow. Thanks again

**Comment by philip-ulrich** [comment]
Looks like there is a little typo that kills the link. :)
http://imgur.com/nWaCJDM

I think that might just depend on how you register your forum URL though. A check when adding url or just a check and add when you output that text should fix. 

Also, the copy link doesn't seem to work for the key in Mac Safari and Firefox. Confirmed working in Chrome on Mac though. 

Another small (insignificant) note is that the page for http://[url]/user/[user]/minecraft has no title and shows as " | NodeBB"

Couple additional side notes, I'm missing plugins/nodebb-plugin-minecraft-integration/public/images/Grass.png on the admin panel and I can't change the avatar source to anything that works. The save button doesn't seem to do anything.

Sorry about the long list. :|

**Comment by yariplus** [comment]
I removed grass.png because of licensing terms. Is it giving you an error?

Also, the avatar settings page works for me. There might be an error on your browser console that's messing it up maybe.

**Comment by philip-ulrich** [comment]
It's mainly just annoying to see the "?" image. Also I'm not seeing any errors in console for that particular issue:
http://imgur.com/ZCG3kwd

The save button just animates, but nothing processes..

**Comment by yariplus** [comment]
Whoa, looks like you have an old version of the forum plugin. Is your nodebb upgraded to v1.0.0 yet? The newer versions are 1.0.0+ only.

**Comment by philip-ulrich** [comment]
It's a clean install on a dev server. Definitely up to date: http://imgur.com/a/OiOB4

I hope you are about to say I should be seeing a lot more configuration because I never found any settings for rank stuff. :D

**Comment by yariplus** [comment]
That admin page is about 4 months old. I'm not sure how that happened, I just did a clean install myself and got the latest one. Try uninstalling and re-installing the plugin, `nodebb-plugin-minecraft-integration`. Make sure the folder gets deleted. The settings are stored in the database, so it shouldn't affect your current settings.

Unfortunately, I have not added many more customization options yet. But it is on my list of things to do once I get 0.7.0 to a stable state.

**Comment by philip-ulrich** [comment]
Did that and I see a slightly different interface. That's really weird... The box has only been up for a few weeks and I grabbed all fresh resources when I installed it a week or two ago. Definitely not 4 months. :)
[root@philip-redis node_modules]# sudo tune2fs -l /dev/xvda1 |grep  'Filesystem created'
Filesystem created:       Wed Feb 17 16:53:19 2016

**Comment by yariplus** [comment]
Strange, might have been a problem with the NodeBB package manager then.

**Comment by philip-ulrich** [comment]
It seems like everything here has been addressed so I'll go ahead and close this out unless you want it open still!

**Comment by yariplus** [comment]
:+1: 
Let me know if you need any other changes made to help with your project.
